### ISSUE TITLE
UnicodeEncodeError from fetch.py

### ISSUE THREAD

**Issue by mrksbrg** [wogscpar/SZZUnleashed#1]
The fetch script results in a UnicodeEncodeError, see below. An empty file "res0.json" is created in the issues subdirectory.

Environment: Python 3.6.6 on Win10.

```
python fetch.py
Total issue matches: 2435
Progress: | = 1000 issues
Traceback (most recent call last):
  File "fetch.py", line 53, in <module>
    fetch()
  File "fetch.py", line 46, in fetch
    f.write(conn.read().decode('utf-8'))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2193' in position 320915: character maps to <undefined>
```

**Comment by wogscpar** [comment]
Can you try to replace

#### f.write(conn.read.decode('utf-8'))
with 
#### f.write(conn.read.decode('utf-8', 'ignore')) 

at row 45? I don't have a windows myself to test this but it should at least give you an output and ignore decoding letters like é and è.

**Comment by mrksbrg** [comment]
f.write(conn.read().decode('utf-8', 'ignore')) didn't make any difference, but I believe the PR should do it. Works on my machine.
