### ISSUE TITLE
Short description of repo and tags need an update

### ISSUE THREAD

**Issue by mrksbrg** [wogscpar/SZZUnleashed#13]
The short description of the repo should be corrected. Instead of 

> A complete implementation of the SZZ algorithm as described by Zeller et al's. 

I suggest

> An implementation of the SZZ algorithm, i.e., an approach to identify bug-introducing commits. 

The reference to the work by the SZZ authors is anyway first in the README.md... on top of that "Zeller et al." is wrong, since it's actually "Śliwerski et al."

Also, I suggest adding a few more tags to support findability of this repo from the software engineering research community. I suggest adding: "defect-prediction", "mining-software-repositories", and "software-engineering-research".

**Comment by EFregnan** [comment]
I agree. This change improves the description clarity. Furthermore, I think the description can also be a little bit misleading since the SZZ version implemented should be the one based on the improvement done by Williams and Spacco and not the original version by Śliwerski et al.

Adding some more tags is a good idea as well. Making the project easier to find is definitely an advantage IMHO.

**Comment by wogscpar** [comment]
Absolutely. Do we have more tags than defect-prediction, mining-software-repositories and software-engineering-research?

**Comment by mrksbrg** [comment]
I think we can start with these. I suggest implementing these minor changes asap.

**Comment by wogscpar** [comment]
I've made some updates regarding this. Please confirm if this is what you excpected @mrksbrg.

**Comment by EFregnan** [comment]
Thank you. One last thing:

> The short description of the repo should be corrected. Instead of
>
> > A complete implementation of the SZZ algorithm as described by Zeller et al's.

This still needs to be changed. If you prefer not to change it to: 

> An implementation of the SZZ algorithm, i.e., an approach to identify bug-introducing commits.

I would suggest to just change Zeller et al. to Śliwerski et al. since otherwise the reference is wrong.

**Comment by wogscpar** [comment]
No, I think the:

An implementation of the SZZ algorithm, i.e., an approach to identify bug-introducing commits.

is better.
