### ISSUE TITLE
cannot find bug fixing issues in Jira Projects of Apache Software Foundation

### ISSUE THREAD

**Issue by davidetaibi** [wogscpar/SZZUnleashed#18]
The analysis of any project in the jira of the apache software foundations fails. 

As example, we executed 

```
git clone https://github.com/apache/accumulo
python3 fetch.py --issue-code ACCUMULO --jira-project issues.apache.org/jira

python3 git_log_to_array.py --repo-path ./accumulo --from-commit 31b54248176f320cc15f432ece29f998a0d3a363

python3 find_bug_fixes.py --gitlog gitlog.json --issue-list ./issues
```

The last script cannot find any matching bug-fixing commit while reading from the commit messages there are several commits reporting the Jira issue id and clearly reporting "fixed" in the commit message.

**Comment by wogscpar** [comment]
This is a bug. There current pattern to match a fix is **'JENKINS-{nbr}\D|#{nbr}\D|HUDSON-{nbr}\D'** which is specific for Jenkins. You have to identify something that indicates that a bug has been solved in the commits and specify that pattern when you run the script *find_bug_fixes.py*. I'm uploading a solution which lets you specify that as an argument.

**Comment by wogscpar** [comment]
@davidetaibi You can try it out by using:

```bash
python3 find_bug_fixes.py --gitlog gitlog.json --issue-list ./issues --gitlog-pattern "<a_pattern>"
```
