### ISSUE TITLE
Using for a GitHub Project

### ISSUE THREAD

**Issue by The-Gupta** [wogscpar/SZZUnleashed#21]
How can it be used for a Public GitHub repository to find bug-fixing commits and the modified code [for any release]?

**Comment by wogscpar** [comment]
If you mean to track issues to commits you should be able to use [Githubs own api](https://developer.github.com/v3/). Unfortunately the current script that finds bug fixes doesn't support github, only JIRA at the moment.

**Comment by mrksbrg** [comment]
I suggest closing this issue. Anyone would be welcome to submit a pull request with support for additional issue trackers.
