### ISSUE TITLE
Unclear Figure 3

### ISSUE THREAD

**Issue by bvasiles** [wogscpar/SZZUnleashed#22]
I'm looking at Figure 3 in your [paper](https://arxiv.org/abs/1903.01742) (BTW, nice graphics!) and I don't understand why line 3 in Commit 3 is not blamed to either Commit 2 or Commit 1.

Could you please clarify?

**Comment by mrksbrg** [comment]
Thanks - and sorry for this late reply! You're absolutely right, line 3 in Commit 3 should be green as in "Inserted line". No history to blame for this line. Thanks for spotting this!

I've at least updated the figure on arXiv now.

@wogscpar: This issue can be closed.
