### ISSUE TITLE
Fetching issues does not work properly

### ISSUE THREAD

**Issue by nyyti** [wogscpar/SZZUnleashed#25]
Jenkins or Jira issues are not downloaded correctly. The fetch.py file's function `fetch` downloads only 50 issues at a time and pagination does not work either as everytime the 50 first issues are downloaded.

I tested the code with several Jira projects and the Jenkins project provided as an example. All tested projects had the same problem.

Apparently the Jira REST API's syntax has changed which causes the problem. I fixed the issue by changing `start_at` to `startAt` and `max_results` to `maxResults`. Example of my fix is below
```
    request = 'https://' + jira_project_name + '/rest/api/2/search?'\
        + 'jql={}&startAt={}&maxResults={}'
```

**Comment by wogscpar** [comment]
Ah yes I can see that in the [jira/docs](https://docs.atlassian.com/software/jira/docs/api/REST/8.3.0/?_ga=2.208602261.668473878.1563865483-1209180965.1560848631#api/2/search-search) as well. Thanks for spotting this, I'm pushing a fix right away.
