### ISSUE TITLE
Add parameters to fetch.py script

### ISSUE THREAD

**Issue by EFregnan** [wogscpar/SZZUnleashed#8]
Now _fetch.py_ only works with the Jira repository of the JENKINS project. It could be interesting to allow the script to work with any Jira project. 

I would suggest to pass two parameters when the script is called from command line:

- The code of the project issues in Jira: e.g., _JENKINS_

- The name of the Jira page of the project: e.g., _issues.jenkins-ci.org_

Moreover, a third parameter may allow to configure the end date of the query: currently, it is set to "_2018-02-20 10:34_"

If you agree, I will generate a pull request with the above-mentioned changes.

**Comment by wogscpar** [comment]
Definitely! That would make it much more dynamic to use.
